# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.provision :shell, path: "pg_config.sh"
    config.vm.box = "ubuntu/xenial64"
    # config.vm.box = "ubuntu/trusty32"
    # config.vm.network "public_network"
    # config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
    # config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    # config.vm.network "forwarded_port", guest: 2222, host: 2222, host_ip: "127.0.0.1"
    # config.ssh.forward_agent = true #for sshing to another machine
    config.ssh.forward_x11 = true
    # config.vbguest.auto_update = false #virtualbox guest addins ???
    # Work around disconnected virtual network cable
    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
        # vb.gui = true
        vb.name = "ArgosVM"
        vb.memory = 2048
        vb.cpus = 2
    end
end
